version: '2.3'
services:
  backend:
    image: pcic/wx-files-service:latest
    container_name: "wx-files-service"
    ports:
      - "30598:8000"
    env_file:
      - wx-files-service.env
    volumes:
      - type: bind
        source: /storage/home/tmurdock/public_html/wx_files/
        target: /storage/home/tmurdock/public_html/wx_files/
        read_only: true

networks:
  default:
    external:
      name: pcicbr0
