#! python
from argparse import ArgumentParser
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from wxfs.indexer import index_location


def main(dsn, directories):
    engine = create_engine(dsn)
    Session = sessionmaker(bind=engine)
    session = Session()

    for directory in directories:
        index_location(session, directory)

    session.commit()  # TODO: Move inside index_location?
    session.close()


if __name__ == "__main__":
    parser = ArgumentParser(
        description="Index weather files for a  single location (directory)"
        "into index database"
    )
    parser.add_argument("-d", "--dsn", help="DSN for index database")
    parser.add_argument("directories", nargs="+", help="Directories to process")
    args = parser.parse_args()

    main(dsn=args.dsn, directories=args.directories)
