#! python
from argparse import ArgumentParser
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from wxfs.indexer import index_location_collection


def main(dsn, directory):
    engine = create_engine(dsn)
    Session = sessionmaker(bind=engine)
    session = Session()

    index_location_collection(session, directory)

    session.commit()  # TODO: Move inside index_location?
    session.close()


if __name__ == "__main__":
    parser = ArgumentParser(
        description="Index weather files for a  single location (directory)"
        "into index database"
    )
    parser.add_argument("-d", "--dsn", help="DSN for index database")
    parser.add_argument("directory", help="Collection directory")
    args = parser.parse_args()

    main(dsn=args.dsn, directory=args.directory)
