name: Python CI

on: push

jobs:
  test:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
    - name: Install poetry
      run: |
        wget -O - https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install python dependencies
      run: |
        poetry install --with=dev
    - name: Test with pytest (full)
      if: github.ref == 'refs/heads/master'
      run: |
        poetry run py.test -v --tb=short
    - name: Test with pytest (fast)
      if: github.ref != 'refs/heads/master'
      run: |
        poetry run py.test -m "not slow" -v --tb=short
